recovery keys generated
bharatjarvis/CoinDock pull request #4
Opened 2022-05-23 09:03 UTC by MouliBallanki

2022-05-23 10:11 UTC, bharatjarvis requested changes

2022-05-23 10:11 UTC, bharatjarvis commented on CoinDock-api/app/Enums/recoveryKeyStatus.php
> +    const InActive =   1;
Inactive is a single word

2022-05-23 10:11 UTC, bharatjarvis commented on CoinDock-api/app/Enums/userStatus.php
> +    const InActive =   1;
Inactive is a single word

2022-05-23 10:11 UTC, bharatjarvis commented on CoinDock-api/app/Http/Controllers/V1/RecoveryKeyController.php
> +            'user_id' => 2,//$user->id,
please remove the hardcoded value and uncomment.

2022-05-23 10:11 UTC, bharatjarvis commented on CoinDock-api/app/Http/Controllers/V1/RecoveryKeyController.php
> +            'status' => 1,
for status use Enum values

2022-05-23 10:19 UTC, MouliBallanki commented on CoinDock-api/app/Enums/recoveryKeyStatus.php
> +    const InActive =   1;
done

2022-05-23 10:19 UTC, MouliBallanki commented on CoinDock-api/app/Enums/userStatus.php
> +    const InActive =   1;
done

2022-05-23 10:23 UTC, bharatjarvis commented on CoinDock-api/app/Http/Controllers/V1/RecoveryKeyController.php
> +            "recovery_code" =>$recoveryString,
use ' ' instead of " "

2022-05-23 11:08 UTC, sita7-debug requested changes

2022-05-23 11:08 UTC, sita7-debug commented on CoinDock-api/app/Http/Controllers/V1/RecoveryKeyController.php
> +
Maintain 12 from .env values and Get read from config values.

2022-05-23 11:08 UTC, sita7-debug commented on CoinDock-api/app/Http/Controllers/V1/RecoveryKeyController.php
> +
/**
     * @var array
     */
    protected $encryptable = ['recovery_code'];


Maintain above code in recoveryKey model. So that Don't need to use bcrypt() here.

2022-05-23 11:08 UTC, sita7-debug commented on CoinDock-api/app/Http/Controllers/V1/RecoveryKeyController.php
> +
Please, add some success message here.

2022-05-23 11:08 UTC, sita7-debug commented on CoinDock-api/app/Http/Controllers/V1/RecoveryKeyController.php
> +        ],201);
Here  200, not 201

2022-05-23 11:08 UTC, sita7-debug commented on CoinDock-api/app/Models/V1/RecoveryKey.php
> +
Can you add enum casting into this model please.

2022-05-23 11:08 UTC, sita7-debug commented on CoinDock-api/app/Http/Controllers/V1/RecoveryKeyController.php
> +    {
Where we get $user? I didn't see any related code in routes.

2022-05-23 11:08 UTC, sita7-debug commented on CoinDock-api/app/Enums/userStatus.php
> +{
It must be UserStatus not  userStatus.

2022-05-27 15:19 UTC, sita7-debug approved these changes

2022-05-31 06:51 UTC, bharatjarvis approved these changes

2022-05-31 06:51 UTC, merged